# Implement your install tasks here
# -------------------------------------------------

- name: create cluster config file
  template:
    src: "roles/install-openshift-aws/templates/install-config.yaml.j2"
    dest: "{{ openshift_install_dir }}/{{ cluster_name }}/install-config.yaml"

- name: create cluster
  shell: |
    source env.sh

    ./openshift-install create cluster --dir="{{ openshift_install_dir }}/{{ cluster_name }}"
  args:
    chdir: "roles/install-openshift-aws/files"

- name: check openshift-install pid
  pids:
    name: openshift-install
  register: openshift_install_pids

- name: wait for openshift-install to finish
  wait_for:
    path: "{{ local_kubeconfig_file}}"
    state: present
    timeout: 5400

- name: wait for bootstrap to complete
  shell: |
    source env.sh

    ./openshift-install wait-for bootstrap-complete --dir="{{ openshift_install_dir }}/{{ cluster_name }}"
  args:
    chdir: "roles/install-openshift-aws/files"

- name: wait for the cluster
  shell: |
    source env.sh

    ./openshift-install wait-for install-complete --dir="{{ openshift_install_dir }}/{{ cluster_name }}"
  args:
    chdir: "roles/install-openshift-aws/files"
