# Implement your post-install deployment tasks here
# -------------------------------------------------

- name: copy KUBECONFIG to local location
  copy:
    src: "~/.openshift/{{ cluster_name }}/auth/kubeconfig"
    dest: "~/.kube/{{ cluster_name }}"

- name: remove the env file
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "roles/install-openshift-aws/files/env.sh"
    