- name: configure the OpenShift cluster
  hosts: localhost
  vars:
    # set the following to control the install/uninstall process
    silent: false
    become_override: false
    ACTION: "INSTALL" # INSTALL, UNINSTALL, UPDATE
    
  tasks:
    - name: configure the openshift cluster infrastructure
      include_role:
        name: roles/infra-openshift-aws
      when: cloud_provider == "aws"