# Implement your initial tasks here
# -------------------------------------------------

- name: set the local kubeconfig location
  set_fact:
    local_kubeconfig_file: "~/.kube/{{ cluster_name }}"

# extract some basic cluster information
- name: get DNS information
  k8s_info:
    kubeconfig: "{{ local_kubeconfig_file }}"
    api_version: config.openshift.io/v1
    kind: dns
    name: cluster
  register: r_cluster_dns 

- name: set cluster facts 
  set_fact:
    cluster_base_domain: "{{ r_cluster_dns.resources.0.spec.baseDomain }}"
    cluster_label: "{{ r_cluster_dns.resources.0.spec.privateZone.tags.Name.split('-')[:-1] | join('-') }}"
