# Implement your install deployment tasks here
# -------------------------------------------------

- name: add the x86 machine sets
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - "machine_set_x86a.yml.j2"
    - "machine_set_x86b.yml.j2"
    - "machine_set_x86c.yml.j2"
      