# Implement your install deployment tasks here
# -------------------------------------------------

- name: add the arm machine sets
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - "machineset_arm_a.yml.j2"
    - "machineset_arm_b.yml.j2"
    - "machineset_arm_c.yml.j2"
      