# Implement your install deployment tasks here
# -------------------------------------------------

- name: create gitops namespace
  k8s:
    kind: Namespace
    name: "{{ gitops_namespace }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"

- name: create gitops system instance
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - default-gitops.yml.j2
    - bootstrap-project.yml.j2
    - bootstrap-app.yml.j2