# Implement your install deployment tasks here
# -------------------------------------------------

- name: install gitops operator
  include_role:
    name: roles/install-operator
  vars:
    operator_name: "openshift-gitops-operator"
    operator_subscription_name: "openshift-gitops-operator"
    subscription_channel: "{{ gitops_subscription_channel }}"
    subscription_starting_csv: "{{ gitops_subscription_starting_csv }}"
    operator_deployment_name: "openshift-gitops-operator-controller-manager"
    operator_namespace: "openshift-gitops-operator"
    operator_group_name: "openshift-gitops-operator"
    create_operator_namespace: true
    create_operator_group: true

- name: install pipelines operator
  include_role:
    name: roles/install-operator
  vars:
    operator_name: "openshift-pipelines-operator-rh"
    operator_subscription_name: "openshift-pipelines-operator"
    operator_deployment_name: "openshift-pipelines-operator"

- name: install hashicorp vault operator
  include_role:
    name: roles/install-operator
  vars:
    operator_name: "vault-secrets-operator"
    operator_subscription_name: "vault-secrets-operator"
    subscription_channel: "{{ vault_subscription_channel }}"
    subscription_starting_csv: "{{ vault_subscription_starting_csv }}"
    source: "certified-operators"
    operator_deployment_name: "vault-secrets-operator-controller-manager"

