# Implement your install deployment tasks here
# -------------------------------------------------

- name: install gitops operator
  include_role:
    name: roles/install-operator
  vars:
    operator_name: "openshift-gitops-operator"
    operator_subscription_name: "openshift-gitops-operator"
    subscription_channel: "latest"
    subscription_starting_csv: "openshift-gitops-operator.v1.16.1"
    operator_deployment_name: "openshift-gitops-operator-controller-manager"
    operator_namespace: "openshift-gitops-operator"
    operator_group_name: "openshift-gitops-operator"
    create_operator_namespace: true
    create_operator_group: true

- name: install pipelines operator
  include_role:
    name: roles/install-operator
  vars:
    operator_name: "openshift-pipelines-operator-rh"
    operator_subscription_name: "openshift-pipelines-operator"
    operator_deployment_name: "openshift-pipelines-operator"
    operator_namespace: "{{ default_operator_namespace}}"
    create_operator_namespace: true

- name: install hashicorp vault operator
  include_role:
    name: roles/install-operator
  vars:
    operator_name: "vault-secrets-operator"
    operator_subscription_name: "vault-secrets-operator"
    subscription_channel: "stable"
    subscription_starting_csv: "vault-secrets-operator.v0.10.0"
    source: "certified-operators"
    operator_deployment_name: "vault-secrets-operator-controller-manager"

- name: install keycloak operator
  include_role:
    name: roles/install-operator
  vars:
    operator_name: "rhbk-operator"
    operator_subscription_name: "rhbk-operator"
    subscription_channel: "stable-v26.2"
    subscription_starting_csv: "rhbk-operator.v26.2.4-opr.2"
    operator_deployment_name: "rhbk-operator"
    operator_namespace: "{{ keycloak_namespace}}"
    operator_group_name: "keycloak"
    create_operator_namespace: true
    create_operator_group: true
    manage_all_namespaces: false
