---
# defaults

gitops_subscription_channel: "latest"
gitops_subscription_starting_csv: "openshift-gitops-operator.v1.16.1"

vault_subscription_channel: "stable"
vault_subscription_starting_csv: "vault-secrets-operator.v0.10.0"