# Implement your pre-install deployment tasks here
# -------------------------------------------------

- name: create the default cluster admin group
  shell: |
    oc adm groups new {{ cluster_admin_group }} \
      --kubeconfig="$HOME/.kube/{{ cluster_name }}"

- name: add the cluster-admin ClusterRole to the admin group
  shell: |
    oc adm policy add-cluster-role-to-group cluster-admin {{ cluster_admin_group }} \
      --kubeconfig="$HOME/.kube/{{ cluster_name }}"
